### ISSUE TITLE
Episode images are not rendering

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/2020-10-09-ReprodR-online#1]

**Comment by kristi-sara** [comment]
huh interesting....when we build the site the figures were popping up...

**Comment by torwhite** [comment]
Sorry, just edited the issue title. I see there are files in the fig folder, but they aren't showing up in the episodes site

**Comment by kristi-sara** [comment]
just transferred figs into folder. I checked the workshop now and it appears they are showing up. Please take a look on your end.

**Comment by torwhite** [comment]
Looks good now, closing
